[build]
target-dir = "target"
incremental = true
jobs = 8

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "target-cpu=native",
    "-C", "link-dead-code=no",
    "-C", "opt-level=3",
]

[profile.release]
incremental = false

[net]
retry = 3
offline = false

[registries.crates-io]
protocol = "sparse"
