version: '3.8'

# Security overlay - use with: docker compose -f docker-compose.yml -f docker-compose.security.yml up

services:
  redis:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  signer:
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp

  executor:
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp
      - /app/temp

  position_manager:
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp

  dashboard:
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp
      - /app/instance 