global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'production'
    cluster: 'memesnipe-v18'

scrape_configs:
  - job_name: 'executor'
    static_configs:
      - targets: ['executor:9090']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'autonomous_allocator'
    static_configs:
      - targets: ['autonomous_allocator:9090']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'risk_guardian'
    static_configs:
      - targets: ['risk_guardian:9090']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'position_manager'
    static_configs:
      - targets: ['position_manager:9090']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'wallet_guard'
    static_configs:
      - targets: ['wallet_guard:9090']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'signer'
    static_configs:
      - targets: ['signer:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
