global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'executor'
    static_configs:
      - targets: ['executor:9184']
  - job_name: 'signer'
    static_configs:
      - targets: ['signer:8989']
